let idNmber = 1;
let idNmberEn = 50;
export const dataEs = [
  {
    key: idNmber,
    id: "presentacion",
    h1Title: "Mis Proyectos Personales",
    title: "Mis Proyectos Personales",
    src: "/projects",
    desc: "",
    desc2: "",
    srcGit: "",
    srcWeb: "",
    image: "/assets/contact_me.png",
  },
  {
    key: idNmber++,
    id: "vistaensueno",
    h1Title: "Turismo",
    title: "Vista Ensueño Cabañas",
    src: "/projects",
    desc: "Cabañas de temporada en Potrero de Garay",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/vista-ensueno",
    srcWeb: "https://vistaensueno.vercel.app/inicio",
    image: "/assets/vistaensueno.png",
  },
  {
    key: idNmber++,
    id: "mirsu",
    title: "Mirsú Cabañas",
    h1Title: "Turismo",
    src: "/projects",
    desc: "Cabañas en Villa General Belgrano. Mapa de ubicación, links a sitios de interés, sitios de necesidad.",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/cabanias_mirsu",
    srcWeb: "https://cabanasmirsu.vercel.app/",
    image: "/assets/Cabanias-mirsu.png",
  },
  {
    key: idNmber++,
    id: "silandra",
    h1Title: "Sitio Comercial",
    title: "Silandra Alta Costura",
    src: "/projects",
    desc: "Casa de novias en Escobar. Bs.As. Argentina",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Silandra",
    srcWeb: "https://silandra.vercel.app/",
    image: "/assets/silandra.jpeg",
  },
  {
    key: idNmber++,
    id: "portfolio",
    h1Title: "Portfolio",
    title: "Silvina Portfolio",
    src: "/projects",
    desc: "Mi portfolio. Sufrió mas cambios que la economia Argentina",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit:
    "https://github.com/SilviStani/React-Portfolio/tree/main/silvi-portfolio",
    srcWeb: "https://react-portfolio-silvistani.vercel.app",
    image: "/assets/PortadaPortfolio.png",
  },
  {
    key: idNmber++,
    id: "walter",
    h1Title: "Servicios",
    title: "Limpieza Tapizados",
    src: "/projects",
    desc: "Limpieza de Tapizados en Corrientes y Chaco. Argentina.",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Limpieza-Tapizados-Walter",
    srcWeb: "https://limpieza-tapizados-walter.vercel.app",
    image: "/assets/Walter-tapizados.png",
  },
  {
    key: idNmber++,
    id: "estetica",
    h1Title: "Servicios",
    title: "Estetyczna Nadja Szewska",
    src: "/projects",
    desc: "SPA de Estética corporal y facial. Servicio de belleza integral.",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Estetyczna-Nadja-Szewska",
    srcWeb: "https://estetyczna-nadja-szewska.vercel.app/",
    image: "/assets/introPage.jpg",
  },
  {
    key: idNmber++,
    id: "delicias",
    h1Title: "Pasteleria",
    title: "Delicias y Manjares",
    src: "/projects",
    desc: "Las delicias mas exquisitas y frescas de todo Escobar. No dudes en probar :)",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/deliciasymanjares",
    srcWeb: "https://deliciasymanjares.vercel.app/",
    image: "/assets/deliciasymanjares.jpg",
  },
  {
    key: idNmber++,
    id: "vipets",
    h1Title: "Proyecto Estudiantil",
    title: "Vipets",
    src: "/projects",
    src: "/projects",
    desc: "Spa pensada en nuestras queridas mascotas. Acceso rápido a las clinicas 24 hs. Proyecto grupal.",
    desc2: "Desarrollado en: React-Redux, Javascript, Css. Express. SQL. PostgresSQL",
    srcGit: "https://github.com/Navito-py/PF-PuppyPalace",
    srcWeb: "",
    image: "/assets/vipets.png",
  },
  {
    id: "henryapp",
    key: idNmber++,
    h1Title: "Proyecto Estudiantil",
    title: "Food*HenryApp",
    src: "/projects",
    desc: "SPA/Proyecto individual, Henry Bootcamp",
    desc2: "Desarrollado en: React-Redux, Javascript, Css. Express. SQL. PostgresSQL",
    srcGit: "https://github.com/SilviStani/Pi-Food",
    srcWeb: "",
    image: "/assets/foodapp.jpg",
  },
  {
    id: "cronometro",
    key:  idNmber++,
    h1Title: "Proyecto Estudiantil",
    title: "Chronometer",
    src: "/projects",
    desc: "A Single & Simple Chronometer pure redux",
    srcGit: "https://github.com/SilviStani/Chronometer-Countdown-Timer",
    srcWeb: "",
    image: "/assets/chronometer.png",
  },
  {
    id: "to-do",
    key: idNmber++,
    h1Title: "Proyecto Estudiantil",
    title: "TodoList: Vacation",
    src: "/projects",
    desc: "Una Todo list creada a puro vanilla javascript. Sus efectos y estilos en Css.",
    srcGit: "https://github.com/SilviStani/Vacation-TodoList",
    srcWeb: "",
    image: "/assets/Todolist.png",
  },
];
export const dataEn = [
  {
    key: idNmberEn,
    id: "vistaensueno",
    h1Title: "Tourism",
    title: "Vista Ensueño Cabins",
    src: "/projects",
    desc: "Seasonal Cabins located in Potrero de Garay, Cordoba, Argentina",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/vista-ensueno",
    srcWeb: "https://vistaensueno.vercel.app/inicio",
    image: "/assets/vistaensueno.png",
},
{
    key: idNmberEn++,
    id: "mirsu",
    h1Title: "Tourism",
    title: "Mirsu Cabins",
    src: "/projects",
    desc: "Seasonal Cabins located in Villa General Belgrano, Cordoba, Argentina.",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/cabanias_mirsu",
    srcWeb: "https://cabanasmirsu.vercel.app/",
    image: "/assets/Cabanias-mirsu.png",
},
{
    key: idNmberEn++,
    id: "silandra",
    h1Title: "Commerce",
    title: "Silandra Haute Couture",
    src: "/projects",
    desc: "Bridal House located in Escobar, Bs.As. Argentina",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Silandra",
    srcWeb: "https://silandra.vercel.app/",
    image: "/assets/silandra.jpeg",
},
{
    key: idNmberEn++,
    id: "portfolio",
    h1Title: "Portfolio",
    title: "Silvina Portfolio",
    src: "/projects",
    desc: "My Portfolio. Suffer more changes that Argentina's Economy",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit:
    "https://github.com/SilviStani/React-Portfolio/tree/main/silvi-portfolio",
    srcWeb: "https://react-portfolio-silvistani.vercel.app",
    image: "/assets/PortadaPortfolio.png",
},
{
    key: idNmberEn++,
    id: "walter",
    h1Title: "General Services",
    title: "Upholstery Cleaning",
    src: "/projects",
    desc: "Upholstery Cleaning located in Chaco. Argentina.",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Limpieza-Tapizados-Walter",
    srcWeb: "https://limpieza-tapizados-walter.vercel.app",
    image: "/assets/Walter-tapizados.png",
},
{
    key: idNmberEn++,
    id: "estetica",
    h1Title: "General Services",
    title: "Estetyczna Nadja Szewska",
    src: "/projects",
    desc: "Body and Facial aesthetics spa. Comprehensive beauty service",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Estetyczna-Nadja-Szewska",
    srcWeb: "https://estetyczna-nadja-szewska.vercel.app/",
    image: "/assets/introPage.jpg",
},
{
    key: idNmberEn++,
    h1Title: "Bakery",
    id: "delicias",
    title: "Delights and Delicacies",
    src: "/projects",
    desc: "The most Exquisite and Fresh delicacies.",
    desc2: "Developed in: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/deliciasymanjares",
    srcWeb: "https://deliciasymanjares.vercel.app/",
    image: "/assets/deliciasymanjares.jpg",
},
{
    key: idNmberEn++,
    id: "vipets",
    h1Title: "Student Project",
    title: "Vipets",
    src: "/projects",
    src: "/projects",
    desc: "Spa designed for our beloved pets. Emergency services and more",
    desc2: "Developed in: React-Redux, Javascript, Css. Express. SQL. PostgresSQL",
    srcGit: "https://github.com/Navito-py/PF-PuppyPalace",
    srcWeb: "",
    image: "/assets/vipets.png",
},
{
    id: "henryapp",
    key: idNmberEn++,
    h1Title: "Student Project",
    title: "Food*HenryApp",
    src: "/projects",
    desc: "SPA/Individual Project, Henry Bootcamp",
    desc2: "Developed in: React-Redux, Javascript, Css. Express. SQL. PostgresSQL",
    srcGit: "https://github.com/SilviStani/Pi-Food",
    srcWeb: "",
    image: "/assets/foodapp.jpg",
},
{
    id: "cronometro",
    key:  idNmberEn++,
    h1Title: "Student Project",
    title: "Chronometer",
    src: "/projects",
    desc: "A Single & Simple Chronometer pure redux",
    srcGit: "https://github.com/SilviStani/Chronometer-Countdown-Timer",
    srcWeb: "",
    image: "/assets/chronometer.png",
},
{
    id: "to-do",
    key:  idNmberEn++,
    title: "To-Do List: Vacation",
    h1Title: "Student Project",
    src: "/projects",
    desc: "To-Do list, vanilla javascript. Effects and Styles pure Css.",
    srcGit: "https://github.com/SilviStani/Vacation-TodoList",
    srcWeb: "",
    image: "/assets/Todolist.png",
},
];