export const data = [
  // ── Full Stack ───────────────────────────────────────────
  {
    id: 'vipets',
    title: 'Vipets',
    category: 'Full Stack',
    desc: 'Spa para mascotas. Acceso rápido a clínicas 24h. Proyecto grupal.',
    tags: ['React', 'Redux', 'Express', 'PostgreSQL'],
    srcGit: 'https://github.com/Navito-py/PF-PuppyPalace',
    srcWeb: '',
    image: '/assets/vipets.png',
  },
  {
    id: 'henryapp',
    title: 'Food · HenryApp',
    category: 'Full Stack',
    desc: 'SPA individual del bootcamp Henry. Búsqueda, filtrado y creación de recetas.',
    tags: ['React', 'Redux', 'Express', 'PostgreSQL'],
    srcGit: 'https://github.com/SilviStani/Pi-Food',
    srcWeb: '',
    image: '/assets/foodapp.jpg',
  },
  // ── QA Automation ────────────────────────────────────────
  {
    id: 'pom-selenium',
    title: 'POM Selenium',
    category: 'QA Automation',
    desc: 'Proyecto de aprendizaje y práctica de Selenium con C# aplicando el patrón Page Object Model.',
    tags: ['Selenium', 'C#', 'POM', 'QA'],
    srcGit: 'https://github.com/SilviStani/Pom_Seleneium',
    srcWeb: '',
    image: '/assets/pom-selenium.png',
  },
  // ── Frontend ─────────────────────────────────────────────
  {
    id: 'portfolio',
    title: 'Mi Portfolio',
    category: 'Frontend',
    desc: 'Portfolio personal. Sufrió más cambios que la economía Argentina.',
    tags: ['Next.js', 'JavaScript', 'SCSS'],
    srcGit: 'https://github.com/SilviStani/silvina_portfolio',
    srcWeb: 'https://silvina-portfolio.vercel.app',
    image: '/assets/my-webpage.png',
  },
  {
    id: 'azul-profundo',
    title: 'Azul Profundo',
    category: 'Frontend',
    desc: 'Servicio de limpieza de piscinas, tratamientos de agua y asesoramiento para el mantenimiento óptimo.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/azul-profundo',
    srcWeb: 'https://azulprofundo.vercel.app/',
    image: '/assets/azul-profundo.png',
  },
  {
    id: 'body-glow',
    title: 'Body Glow',
    category: 'Frontend',
    desc: 'Sitio web para Body Glow, centro de estética y bienestar corporal.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/Body_Glow',
    srcWeb: 'https://body-glow.vercel.app/',
    image: '/assets/body-glow.png',
  },
  {
    id: 'walter',
    title: 'Walter Limpieza Tapizados',
    category: 'Frontend',
    desc: 'Limpieza de Tapizados en Corrientes y Chaco, Argentina.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/walter-limpieza-tapizados-migration',
    srcWeb: 'https://limpieza-tapizados-walter.vercel.app',
    image: '/assets/Walter-tapizados.png',
  },
  {
    id: 'vistaensueno',
    title: 'Vista Ensueño Cabañas',
    category: 'Frontend',
    desc: 'Cabañas de temporada en Potrero de Garay',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/vista-ensueno',
    srcWeb: 'https://vistaensueno.vercel.app/inicio',
    image: '/assets/vistaensueno.png',
  },
  {
    id: 'estetica',
    title: 'Estetyczna Nadja Szewska',
    category: 'Frontend',
    desc: 'SPA de estética corporal y facial. Servicio de belleza integral.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/Estetyczna-Nadja-Szewska',
    srcWeb: 'https://estetyczna-nadja-szewska.vercel.app/',
    image: '/assets/introPage.jpg',
  },
  {
    id: 'silandra',
    title: 'Silandra Alta Costura',
    category: 'Frontend',
    desc: 'Casa de novias en Escobar, Buenos Aires, Argentina.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/Silandra',
    srcWeb: 'https://silandra.vercel.app/',
    image: '/assets/silandra.jpeg',
  },
  {
    id: 'mirsu',
    title: 'Mirsú Cabañas',
    category: 'Frontend',
    desc: 'Cabañas en Villa General Belgrano. Mapa de ubicación y links de interés.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/cabanias_mirsu',
    srcWeb: 'https://cabanasmirsu.vercel.app/',
    image: '/assets/Cabanias-mirsu.png',
  },
  {
    id: 'delicias',
    title: 'Delicias y Manjares',
    category: 'Frontend',
    desc: 'Panadería artesanal en Escobar. Catálogo digital y contacto directo.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/deliciasymanjares',
    srcWeb: 'https://deliciasymanjares.vercel.app/',
    image: '/assets/deliciasymanjares.jpg',
  },
  {
    id: 'mi-terra',
    title: 'Mi Terra',
    category: 'Frontend',
    desc: 'Sitio web en desarrollo. Próximamente disponible.',
    tags: ['Next.js', 'JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/miterra',
    srcWeb: '',
    image: '/assets/my-webpage.png',
  },
  // ── Vanilla JS ───────────────────────────────────────────
  {
    id: 'cronometro',
    title: 'Chronometer',
    category: 'Vanilla JS',
    desc: 'Cronómetro con cuenta regresiva. Puro Redux, sin frameworks.',
    tags: ['JavaScript', 'Redux', 'CSS'],
    srcGit: 'https://github.com/SilviStani/Chronometer-Countdown-Timer',
    srcWeb: '',
    image: '/assets/Counter.jpg',
  },
  {
    id: 'to-do',
    title: 'TodoList: Vacation',
    category: 'Vanilla JS',
    desc: 'Todo list de planificación de vacaciones en Vanilla JavaScript.',
    tags: ['JavaScript', 'CSS'],
    srcGit: 'https://github.com/SilviStani/Vacation-TodoList',
    srcWeb: '',
    image: '/assets/Todolist.png',
  },
];
