let idNmber = 1;
export const data = [
  {
    id: idNmber++,
    title: "All",
    src: "/projects",
    desc: "",
    desc2: "",
    srcGit: "",
    srcWeb: "",
    image: "",
  },
  {
    id: idNmber++,
    title: "Vista Ensueño Cabañas",
    src: "/projects",
    desc: "Cabañas de temporada en Potrero de Garay",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/vista-ensueno",
    srcWeb: "https://vistaensueno.vercel.app/inicio",
    image: "/assets/vistaensueno.png",
  },
  {
    id: idNmber++,
    title: "Silandra Alta Costura",
    src: "/projects",
    desc: "Casa de novias en Escobar. Bs.As. Argentina",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Silandra",
    srcWeb: "https://silandra.vercel.app/",
    image: "/assets/silandra.jpeg",
  },
  {
    id: idNmber++,
    title: "Mirsú Cabañas",
    src: "/projects",
    desc: "Cabañas en Villa General Belgrano. Mapa de ubicación, links a sitios de interés, sitios de necesidad.",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/cabanias_mirsu",
    srcWeb: "https://cabanasmirsu.vercel.app/",
    image: "/assets/Cabanias-mirsu.png",
  },
  {
    id: idNmber++,
    title: "Mi Portfolio",
    src: "/projects",
    desc: "Mi portfolio. Sufrió mas cambios que la economia Argentina",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit:
    "https://github.com/SilviStani/React-Portfolio/tree/main/silvi-portfolio",
    srcWeb: "https://react-portfolio-silvistani.vercel.app",
    image: "/assets/PortadaPortfolio.png",
  },
  {
    id: idNmber++,
    title: "Walter Limpieza Tapizados",
    src: "/projects",
    desc: "Limpieza de Tapizados en Corrientes y Chaco. Argentina.",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Limpieza-Tapizados-Walter",
    srcWeb: "https://limpieza-tapizados-walter.vercel.app",
    image: "/assets/Walter-tapizados.png",
  },
  {
    id: idNmber++,
    title: "Estetyczna Nadja Szewska",
    src: "/projects",
    desc: "SPA de Estética corporal y facial. Servicio de belleza integral.",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/Estetyczna-Nadja-Szewska",
    srcWeb: "https://estetyczna-nadja-szewska.vercel.app/",
    image: "/assets/introPage.jpg",
  },
  {
    id: idNmber++,
    title: "Delicias y Manjares",
    src: "/projects",
    desc: "Las delicias mas exquisitas y frescas de todo Escobar. No dudes en probar :)",
    desc2: "Desarrollado en: Next.Js, Javascript, Css.",
    srcGit: "https://github.com/SilviStani/deliciasymanjares",
    srcWeb: "https://deliciasymanjares.vercel.app/",
    image: "/assets/3.jpg",
  },
  {
    id: idNmber++,
    title: "Vipets",
    src: "/projects",
    src: "/projects",
    desc: "Spa pensada en nuestras queridas mascotas. Acceso rápido a las clinicas 24 hs. Proyecto grupal.",
    desc2: "Desarrollado en: React-Redux, Javascript, Css. Express. SQL. PostgresSQL",
    srcGit: "https://github.com/Navito-py/PF-PuppyPalace",
    srcWeb: "",
    image: "/assets/vipets.png",
  },
  {
    id: idNmber++,
    title: "Food*HenryApp",
    src: "/projects",
    desc: "SPA/Proyecto individual, Henry Bootcamp",
    desc2: "Desarrollado en: React-Redux, Javascript, Css. Express. SQL. PostgresSQL",
    srcGit: "https://github.com/SilviStani/Pi-Food",
    srcWeb: "",
    image: "/assets/foodapp.jpg",
  },
  {
    id: idNmber++,
    title: "Chronometer",
    src: "/projects",
    desc: "A Single & Simple Chronometer pure redux",
    srcGit: "https://github.com/SilviStani/Chronometer-Countdown-Timer",
    srcWeb: "",
    image: "/assets/chronometer.png",
  },
  {
    id: 11,
    title: "TodoList: Vacation",
    src: "/projects",
    desc: "Una Todo list creada a puro vanilla javascript. Sus efectos y estilos en Css.",
    srcGit: "https://github.com/SilviStani/Vacation-TodoList",
    srcWeb: "",
    image: "/assets/Todolist.png",
  },
];